### ISSUE TITLE
get_cosine_similarity 함수의 test 관련

### ISSUE THREAD

**Issue by bizli0618** [jdasam/aat3020-2023#2]
assert 부분의 test는 similarity 가 -1과 1 사이에 있는 지를 확인하고 있는데, error 메시지는 "Similarity has to be between 0 and 1"로 되어있습니다. 
확인 부탁드립니다.

**Comment by jdasam** [comment]
안녕하세요, 그 부분은 에러 메시지가 잘못된 것이 맞습니다. -1과 1 사이의 값이 나오는게 맞습니다. 수정해두었습니다.
